[package]
name = "nil"
description = "Noxmore's Ixperimental Lutilities"
version = "0.13.3"
edition = "2021"
authors = ["Noxmore"]
repository = "https://github.com/Noxmore/nil"
readme = "README.md"
license = "MIT OR Apache-2.0"
categories = ["rust-patterns"]

[dependencies]
once_cell = "1"
smart-default = "0.7"
parking_lot = { version = "0.12", features = ["hardware-lock-elision"] }
